version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3 
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - rabbitmq.env 
    networks:
      - network

  memcached:
    image: memcached:alpine
    hostname: memcached
    networks:
      - network

  awx:
    image: ansible/awx_task:latest
    user: root
    env_file:
      - awx.env
    networks:
      - network
    #volumes:
    #  - ./connection.py:/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py

  awx_web:
    image: ansible/awx_web:latest
    hostname: awxweb
    user: root
    ports:
      - "80:8052"
    env_file:
      - awx.env
    networks:
      - network
    #volumes:
    #  - ./connection.py:/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py

networks:
  network:

volumes:
  postgres:
